# Generated by Django 4.0.6 on 2022-08-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minted', models.BooleanField(default=False)),
                ('ipfs_CID', models.CharField(default='', max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('background', models.CharField(max_length=300)),
                ('head', models.CharField(max_length=300)),
                ('tone', models.CharField(max_length=300)),
                ('gang', models.CharField(max_length=300)),
                ('expression', models.CharField(max_length=300)),
                ('hair', models.CharField(max_length=300)),
                ('hair_color', models.CharField(max_length=300)),
                ('shoes', models.CharField(blank=True, max_length=300, null=True)),
                ('right_hand', models.CharField(blank=True, max_length=300, null=True)),
                ('left_hand', models.CharField(blank=True, max_length=300, null=True)),
                ('ear_style', models.CharField(blank=True, max_length=300, null=True)),
                ('neck_style', models.CharField(blank=True, max_length=300, null=True)),
                ('chest_style', models.CharField(blank=True, max_length=300, null=True)),
                ('face_style', models.CharField(blank=True, max_length=300, null=True)),
                ('mark', models.CharField(blank=True, max_length=300, null=True)),
                ('total_features', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
